### ISSUE TITLE
[BE] SMTP 메일 서버 연동

### ISSUE THREAD

**Issue by kioku714** [JAVACAFE-STUDY/chainity#264]

**Comment by kioku714** [comment]
https://extrememanual.net/30287

**Comment by rygh4775** [comment]
`javacafe.co.kr` -> `chainity.co.kr`변경 해주세요.

**Comment by rygh4775** [comment]
@kioku714 
보내는 메일 리스트
- notification@chainity.co.kr
받는 메일 리스트
- contact@chainity.co.kr

**Comment by rygh4775** [comment]
TODO
chainity.co.kr 체크

www.chainity.co.kr -> ladning
chainity.co.kr -> landing
api.chainity.co.kr -> api
*.chainity.co.kr  -> web
