### ISSUE TITLE
[IF] 신규 도메인 구입 

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/chainity#269]
chainity.co.kr 도메인 구입 및 IP 연동

**Comment by kioku714** [comment]
TODO
chainity.co.kr 체크

www.chainity.co.kr -> landing
chainity.co.kr -> landing
api.chainity.co.kr -> api
*.chainity.co.kr -> web

**Comment by rygh4775** [comment]
@kioku714 
위 포트 맵핑은 nginx 설정 관련 별도 이슈 만들어 진행하겠습니다.
아래 도메인 IP 연동 부분만 진행해주세요.
- [ ] chainity.co.kr -> 54.180.59.99
- [ ] *.chainity.co.kr -> 54.180.59.99
