### ISSUE TITLE
[ALL] 로고 이미지 구입

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/chainity#270]
Chainity 로고 이미지 구입 및 적용

로고 판매 사이트
- https://studio.tailorbrands.com/
- https://logomaster.ai

**Comment by rygh4775** [comment]
@kioku714 @clghks  가격 정책이 다 다른데요. 예상 비용은 1~3만원 정도 될 것 같네요.
### logomaster
![image](https://user-images.githubusercontent.com/1798539/57671720-e5b74d00-764f-11e9-80b0-07078f6c10c7.png)
![image](https://user-images.githubusercontent.com/1798539/57671735-fbc50d80-764f-11e9-91ac-bb33985559f3.png)
### tailorbrands
![image](https://user-images.githubusercontent.com/1798539/57671888-97ef1480-7650-11e9-94b5-e0c89d4d5fdf.png)

**Comment by kioku714** [comment]
https://drive.google.com/open?id=1W5FU3lZp-TKmWB3i8G7EY1ecP716OKm0
